### ISSUE TITLE
Fix font on speaker and schedule page

### ISSUE THREAD

**Issue by ShyamGadde** [ShyamGadde/styles-conference#1]

**Comment by JioBautista** [comment]
Hey, I'm checking out your page (looks good btw) I was wondering which styles specifically you want to fix?

**Comment by ShyamGadde** [comment]
@JioBautista Thanks for checking out my page and for your feedback. I appreciate it. The styles I want to fix are mainly the fonts. The Google fonts are not being imported correctly on the schedule and speakers page, so they are using a different font than the one I intended. You can refer to the head element of the index page to see how I imported the Google fonts. And yes, making the page responsive would be great too.

**Comment by JioBautista** [comment]
I reviewed your code base and inspected the pages you described. The fonts are working properly according to what you imported.

**Comment by ShyamGadde** [comment]
Hey @JioBautista, I think I might have found the issue.
I was just looking at the console and found this:

```
Mixed Content: The page at 'https://shyamgadde.github.io/styles-conference/schedule.html' was loaded 
over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Lato:100,300,400'. 
This request has been blocked; the content must be served over HTTPS.
```

I tested it in Firefox, and it worked fine there, but not in Chromium browsers, like Google Chrome or Microsoft Edge. Maybe it works in Safari as well, I guess. So, I just quickly checked Google Fonts and how they recommend we import the fonts and made the necessary changes to import the fonts the right way. I have pushed the changes to the repository. 

I'll go ahead and close this issue now. Thank you for taking the time to review the code.

Hey, by the way, if you are interested, I'd love to hear your ideas on how to make the site mobile responsive.

**Comment by JioBautista** [comment]
Yeah, I was using Chrome and the fonts were showing up properly and I'm 100% interested. I already have ideas in terms of layout. Are you familiar with flexbox and grid layouts?

**Comment by ShyamGadde** [comment]
Cool! Yes, I'm familiar with them.

**Comment by JioBautista** [comment]
Okay sounds good. I'll work on it at another branch and you can review the code to see if you like it.
